name: mobile_chat
version: 0.3.0+3
publish_to: none

description: Flutter group chat app for Android and iOS.

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  flutter_secure_storage: ^9.2.2

flutter:
  uses-material-design: true
