name: mobile_chat
version: 0.5.0+5
publish_to: none

description: Koom civic communication app for Android and iOS.

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.3
  web_socket_channel: ^3.0.1
  firebase_core: ^3.8.0
  firebase_messaging: ^15.1.5
  flutter_local_notifications: ^22.0.1
  mobile_scanner: ^7.0.0
  qr_flutter: ^4.1.0
  file_picker: ^8.3.7
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
